github_repo: "jrnold/r4ds-exercise-solutions"
deploy_url: "https://jrnold.github.io/r4ds-exercise-solutions/"
r4ds:
  github_repo: "hadley/r4ds"
  url: "https://r4ds.had.co.nz"
chapters:
  - {"rmd": "intro.Rmd", "html": "introduction.html"}
  - {"rmd": "explore-intro.Rmd", "html": "explore-intro.html"}
  - {"rmd": "visualize.Rmd", "html": "data-visualisation.html"}
  - {"rmd": "workflow-basics.Rmd", "html": "workflow-basics.html"}
  - {"rmd": "transform.Rmd", "html": "transform.html"}
  - {"rmd": "workflow-scripts.Rmd", "html": "workflow-scripts.html"}
  - {"rmd": "EDA.Rmd", "html": "exploratory-data-analysis.html"}
  - {"rmd": "workflow-projects.Rmd", "html": "workflow-projects.html"}
  - {"rmd": "wrangle-intro.Rmd", "html": "wrangle-intro.html"}
  - {"rmd": "tibble.Rmd", "html": "tibbles.html"}
  - {"rmd": "import.Rmd", "html": "data-import.html"}
  - {"rmd": "tidy.Rmd", "html": "tidy-data.html"}
  - {"rmd": "relational-data.Rmd", "html": "relational-data.html"}
  - {"rmd": "strings.Rmd", "html": "strings.html"}
  - {"rmd": "factors.Rmd", "html": "factors.html"}
  - {"rmd": "datetimes.Rmd", "html": "dates-and-times.html"}
  - {"rmd": "program-intro.Rmd", "html": "program-intro.html"}
  - {"rmd": "pipes.Rmd", "html": "pipes.html"}
  - {"rmd": "functions.Rmd", "html": "functions.html"}
  - {"rmd": "vectors.Rmd", "html": "vectors.html"}
  - {"rmd": "iteration.Rmd", "html": "iteration.html"}
  - {"rmd": "model-intro.Rmd", "html": "model-intro.html"}
  - {"rmd": "model-basics.Rmd", "html": "model-basics.html"}
  - {"rmd": "model-building.Rmd", "html": "model-building.html"}
  - {"rmd": "many-models.Rmd", "html": "many-models.html"}
  - {"rmd": "communicate-intro.Rmd", "html": "communicate-intro.html"}
  - {"rmd": "rmarkdown.Rmd", "html": "r-markdown.html"}
  - {"rmd": "graphics-for-communication.Rmd", "html": "graphics-for-communication.html"}
  - {"rmd": "rmarkdown-formats.Rmd", "html": "r-markdown-formats.html"}
  - {"rmd": "rmarkdown-workflow.Rmd", "html": "r-markdown-workflow.html"}
exercise_sections:
  # Mapping from subsections to the Exercise subsubsection in R4DS
  3.1: 1
  3.2: 4
  3.3: 1
  3.5: 1
  3.6: 1
  3.8: 1
  3.9: 1
  5.2: 4
  5.3: 1
  5.4: 1
  5.5: 2
  5.6: 7
  5.7: 1
  7.3: 4
  7.4: 1
  7.5.1: 1
  7.5.2: 1
  7.5.3: 1
  11.2: 2
  11.3: 5
  11.4: 1
  12.2: 1
  12.3: 3
  12.4: 3
  12.5: 1
  12.6: 1
  13.2: 1
  13.3: 1
  13.4: 6
  13.5: 1
  14.2: 5
  14.3.1: 1
  14.3.2: 1
  14.3.3: 1
  14.3.4: 1
  14.3.5: 1
  14.4.3: 1
  14.4.4: 1
  14.4.5: 1
  14.5: 1
  14.7: 1
  15.3: 1
  15.4: 1
  15.5: 1
  16.2: 4
  16.3: 4
  16.4: 5
  19.2: 1
  19.3: 1
  19.4: 4
  19.5: 5
  20.3: 5
  20.4: 6
  20.5: 4
  20.7: 4
  21.2: 1
  21.3: 5
  21.4: 1
  21.5: 3
  21.9: 3
  23.2: 1
  23.3: 3
  23.4: 5
  24.2: 3
  24.3: 5
  25.2: 5
  25.4: 5
  25.5: 3
  27.2: 1
  27.3: 1
  27.4: 7
  28.2: 1
  28.3: 1
  28.4: 4
